@startuml home_workout_planner_S3
left to right direction

actor User as user

rectangle "Home Workout Planner" {
usecase "Create Personal Profile" as UC1
usecase "Take Fitness Assessment" as UC2
}

user -- UC2
UC2 ..> UC1:<<include>>

@enduml
